# Generated by Django 3.1.2 on 2020-10-04 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201003_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('html', 'HTML'), ('mark', 'Markdown')], default=django.utils.timezone.now, help_text='Select Content Language', max_length=20),
            preserve_default=False,
        ),
    ]
