# Generated by Django 3.1.2 on 2020-10-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('html', 'HTML'), ('mark', 'Markdown')], default='html', help_text='Select Content Language', max_length=20),
        ),
    ]
