# Generated by Django 3.0.5 on 2020-04-11 04:27

from django.db import migrations
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body2',
            field=markdownx.models.MarkdownxField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
