# Generated by Django 3.0.5 on 2020-04-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_body2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body2',
        ),
    ]
