# Generated by Django 3.1.2 on 2020-10-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201005_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_content',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
