# Generated by Django 3.0.6 on 2020-05-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_highlightcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightcode',
            name='body_highlighted',
            field=models.TextField(blank=True),
        ),
    ]
